Update ci-modus-build.yml

diff --git a/.github/workflows/ci-modus-build.yml b/.github/workflows/ci-modus-build.yml
--- a/.github/workflows/ci-modus-build.yml
+++ b/.github/workflows/ci-modus-build.yml
@@ -1,37 +1,58 @@
-name: CI for Modus Build
+name: ci-modus-build
 
 on:
+  workflow_dispatch:
+  pull_request:
   push:
     branches:
-      - main  # Trigger this workflow on push to 'main' branch
-  pull_request:
-    branches:
-      - main  # Trigger this workflow on pull requests to 'main' branch
+      - main
+
+env:
+  MODUS_DIR: ""
+
+permissions:
+  contents: read
 
 jobs:
   build:
-    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu machine
-
+    name: build
+    runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2  # Checkout the repository code
+        uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
+      - name: Locate directory with modus.json
+        id: set-dir
+        run: |
+          MODUS_JSON=$(find $(pwd) -name 'modus.json' -print0 | xargs -0 -n1 echo)
+          if [ -n "$MODUS_JSON" ]; then
+            MODUS_DIR=$(dirname "$MODUS_JSON")
+            echo "MODUS_DIR=$MODUS_DIR" >> $GITHUB_ENV
+          else
+            echo "modus.json not found"
+            exit 1
+          fi
+
+      - name: Setup Node
+        uses: actions/setup-node@v4
         with:
-          node-version: '22'  # You can set the Node.js version according to your needs
+          node-version: "22"
 
-      - name: Install Dependencies
-        run: |
-          npm install -g @hypermode/modus-cli  # Install the Modus CLI globally
-          npm install  # Install dependencies from package.json
+      - name: Setup Go
+        uses: actions/setup-go@v5
 
-      - name: Build Modus App
-        run: modus dev  # Run the Modus app build/development process
+      - name: Setup TinyGo
+        uses: acifani/setup-tinygo@v2
+        with:
+          tinygo-version: "0.34.0"
 
-      - name: Push Changes and Deploy (if applicable)
-        run: |
-          git config --global user.name 'MukeshAofficial'  # Set Git user name
-          git config --global user.email 'mukeshofficial685@gmail.com'  # Set Git email
-          git commit -am "Trigger deployment"  # Commit changes if any
-          git push origin main  # Push to GitHub (could trigger deployment)
+      - name: Build project
+        run: npx -p @hypermode/modus-cli -y modus build
+        working-directory: ${{ env.MODUS_DIR }}
+        shell: bash
+
+      - name: Publish GitHub artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: build
+          path: ${{ env.MODUS_DIR }}/build/*
